// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knfjlswciyqibifzckww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtuZmpsc3djaXlxaWJpZnpja3d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NzAyMDYsImV4cCI6MjA3MzQ0NjIwNn0.UWAH2sPJS3ws8O7VzkqEBKudLo1GcX78AMOwAtP4mb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});